version: '3.8'

services:
  # 后端API服务
  backend:
    build: .
    container_name: meedu-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # 数据库文件持久化
      - ./data:/app/data
      # 日志文件持久化
      - ./logs:/app/logs
      # 上传文件持久化
      - ./uploads:/app/uploads
      # 数据库文件映射（生产环境）
      - ./training.db:/app/training.db
      # 排除node_modules，使用容器内的
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-in-production}
      - SESSION_SECRET=${SESSION_SECRET:-your-session-secret-change-in-production}
    env_file:
      - .env
    networks:
      - meedu-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  meedu-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  data:
    driver: local
  logs:
    driver: local
  uploads:
    driver: local
